application: taevals-cs
version: 2
runtime: python27
api_version: 1
threadsafe: true

admin_console:
  pages:
  - name: TA Evals Admin Page
    url: /admin

#builtins:
#- appstats: on
#- remote_api: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /admin.*
  script: taevals.app
  login: admin
  secure: always

- url: /eval/[0-9a-f]+
  script: taevals.app
  secure: always

- url: /.*
  script: taevals.app
  secure: never

libraries:
- name: jinja2
  version: 2.6
